# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FruitTree' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FruitTree
  
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Eureka', '~> 4.0'

  target 'FruitTreeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FruitTreeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
